//Tällä määritetään kappaleiden järjestys, määrittelemättömät laitetaan listan loppuun
export const songsInOrder = [
  "helan går",
  "ystävä sä snapsien",
  "tänään otetaan",
  "pienet käärmeet",
  "silja line special",
  "minnet",
  "KO-KO-KO-KOSKENKOKOKO-KORVAA",
  "pikku kakkonen",
  "vi ska dricka hela natten",
  "syksyn juomasävel",
  "Nyt",
  "sörnai gusha",
  "saku sammakko",
  "testamentti",
  "lapin kulta",
  "jos (e)ukkosi kieltää sua juomasta",
  "oodi sitoutumattomuudelle",
  "koff",
  "fuksipuksi",
  "skumppaa punkun kaa",
  "yogi bear",
  "macarena",
  "brännvin, vatten",
  "pohjois-karjala",
  "finlandia",
  "ken ompi fuksi...",
  "krapulan enkeli",
  "eurovision",
  "jallutähden alla",
  "mies ulos sinusta",
  "ievan polkka",
  "jääkärimarssi",
  "en liten snapvisa",
  "lyhyt turkulainen juomalaulu",
  "juomalaulu laulutaidottomille",
  "sen siiderin",
  "hengaillaan",
  "ukkometso",
  "meistä tuli koodareita",
  "vitutuslaulu",
  "bittilaulu",
  "karhuviinaa ja savon wiinaa",
  "ei tippa tapa",
  "r-kioski mainosjingle",
  "ankronikka",
  "koodaribiisi",
  "felix mainosjingle",
]
